### ISSUE TITLE
How to start training with completely new, unlabelled dataset

### ISSUE THREAD

**Issue by harveyng** [KeremTurgutlu/self_supervised#11]
Hi, I saw the example code but it is for the labeled dataset. I wonder how should I start training with a completely fresh unlabelled dataset. 

It would be great if you could give a sample code for it. Thanks

**Comment by KeremTurgutlu** [comment]
Hi, you can simply create dummy labels for whatever data you have. Anyway, those labels are not used during self-supervised learning so can be ignored.

**Comment by KeremTurgutlu** [comment]
I would suggest checking out https://docs.fast.ai/ and https://forums.fast.ai/ if you have trouble creating data with fastai data API.

**Comment by harveyng** [comment]
Thank @KeremTurgutlu , i 'll give it a try.
