### ISSUE TITLE
Training encoder on pretrained resnet

### ISSUE THREAD

**Issue by bibs2091** [KeremTurgutlu/self_supervised#13]
Hello, my question is that is it better (or okay) to train our encoder using the algorithms of this repo using a pretrained model such as resnet18?
![image](https://user-images.githubusercontent.com/28659618/94754000-eb6a1b80-0387-11eb-9bee-8aa16389ad84.png)

**Comment by KeremTurgutlu** [comment]
@bibs2091 Yes, it’s usually a good idea to start training from a pretrained model. Always try all of your ideas and see which works better!

In ImageWang benchmark we are not allowed to use ImageNet pretrained models since it would be a data leak.

Hope this helps!
