### ISSUE TITLE
Add a GitHub Discussion for this project

### ISSUE THREAD

**Issue by kai-tub** [KeremTurgutlu/self_supervised#17]
Hey,

Would you consider opening a public forum for this repository?
I would've easily missed the great discussions in #16 if I wouldn't have read the issue section.
For these types of questions and answers, I would recommend using the [GitHub discussion section](https://docs.github.com/en/discussions).

Then maybe others could also contribute explanations for parts that they had a hard time understanding.
For example, it took me some time to realize what the following line of code was doing:
```python
csim = F.cosine_similarity(inp, inp.unsqueeze(dim=1), dim=-1)/self.temp
```
Until I've realized that the `cosine_similarity` function of `torch` is _weird_ and doesn't behave like the SciPy version (i.e. calculating the cosine similarity for all _vector pairs_).

That would be something I would like to add to the discussion section.

What is your opinion?

PS: Then again, maybe I am just too _new_ to the field and it was obvious for everyone else.

**Comment by KeremTurgutlu** [comment]
I didn't know about Github discussion, thanks for pointing it out! I labeled #16 as discussion and tried to follow steps on [Converting issues based on labels](https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions-in-your-repository#converting-issues-based-on-labels) but I am unable to see the **Convert issues** button.

**Comment by KeremTurgutlu** [comment]
Discussions page is created.
