### ISSUE TITLE
Question about unlabelled dataset.

### ISSUE THREAD

**Issue by tcapelle** [KeremTurgutlu/self_supervised#23]
Hey nice work you have put here!
As I see on the notebooks, you always train with a labelled dataset. (`tfms = [ParentLabeller, Categorize]`).
Is this really needed?
Would you mind sharing a notebooks with the pretraining on an unlabelled dataset?

**Comment by KeremTurgutlu** [comment]
Thank you! No it can be a dataset without labels. So you can just replace label transforms with something like [lambda x: return x]. I can add a notebook later too.
