### ISSUE TITLE
Wrong `max_n` value in SimCLR fastai_update branch

### ISSUE THREAD

**Issue by kai-tub** [KeremTurgutlu/self_supervised#32]
Thanks for updating the show method so quickly!
But I think you've made a typo in SimCLR:
```python
    @torch.no_grad()
    def show(self, n=1):
        bs = self.learn.x.size(0)//2
        x1,x2  = torch.split(self.learn.x, [bs,bs])
        idxs = np.random.choice(range(bs),n,False)
        x1 = self.aug1.decode(x1[idxs].to('cpu').clone()).clamp(0,1)
        x2 = self.aug2.decode(x2[idxs].to('cpu').clone()).clamp(0,1)
        images = []
        for i in range(n): images += [x1[i],x2[i]] 
        return show_batch(x1[0], None, images, max_n=n * n, ncols=None, nrows=n)
```
`max_n` shouldn't be `n * n` but `2n`.
This will not impact the functionality but is technically wrong.
I would suggest simply using `max_n=len(images)`.
Then it will never be _out-of-sync_ and it would be more obvious. 

Sadly it still doesn't work for my special tensor class, because `torch.split` seems to remove the metadata information of the fastai tensor classes...
But that is either a bug in torch/fastai and not in your code base. :)

**Comment by kai-tub** [comment]
And in `show_one` from SWAV you are clipping to min=0.1 and not min=0, max=1

```python
@torch.no_grad()
    def show_one(self):
        xb = self.learn.xb[0]
        i = np.random.choice(self.bs)
        # by mistake you wrote clamp(0.1) instead of clamp(0, 1)
        images = [aug.decode(b.to('cpu').clone()).clamp(0.1)[i] 
                      for b, aug in zip(xb, self.augs)]
        return show_batch(xb[0], None, images, max_n=len(images), ncols=len(images), nrows=1)
```

**Comment by KeremTurgutlu** [comment]
> Sadly it still doesn't work for my special tensor class, because torch.split seems to remove the metadata information of the fastai tensor classes...
> But that is either a bug in torch/fastai and not in your code base. :)

Can you provide an example, e.g. once you apply `torch.split` the type is no longer the custom type you created?

**Comment by kai-tub** [comment]
Yes, regular indexing would solve my issue.
But I don't want to enforce a workaround just for my code and am very biased towards using regular indexing.
As this `torch.split` issue may not be considered an actual issue.
It may be considered expected behavior, but like I said this is a question for the fastai maintainers :)
For reference, this is the Colab notebook I will link to on the fastai issue page:

https://colab.research.google.com/drive/1-qBwSnyFaNLNMQsoFKbtd0fftiIEvLSH?usp=sharing

So you might _just_ be making me happy be removing `torch.split` and using regular indexing. :D

**Comment by kai-tub** [comment]
See the discussion in the fastai forums [here](https://forums.fast.ai/t/torch-split-removes-metadata/86548)

**Comment by KeremTurgutlu** [comment]
Hmm.. thanks for sharing code example. That may be due to torch.split
