### ISSUE TITLE
Proposal: Remove implicit augmentation-building pipeline in callbacks

### ISSUE THREAD

**Issue by kai-tub** [KeremTurgutlu/self_supervised#33]
This is definitely a topic where it will come down to your personal preference.
_In my opinion_, I would remove the initialization of the augmentation functions in the callbacks.

### From a new user perspective
Let's take a look from the perspective of a new user.
I am a developer who has never really done anything with self-supervised learning.
I notice your repository because it uses fastai and is awesome. ;)
After skimming the documentation, I decided to test it out with SimCLR and see that I only need to use your Callback.
If I've already worked with MixUp the callback style is familiar to me.
So I build up my item_tfm and batch_tfm pipeline.
I use your SWAV() callback without any changes as it already has default values for everything.
At this point, I may still haven't realized that these models have a _special augmentation_ pipeline and that the augmentation is crucial for the performance.
If the user skips to the _Example usage_ section, they may miss the _building a data-augmentation pipeline_ step.

I understand the desire to use a single transformation pipeline for all models and to give the user the ability to very quickly train the model in an unsupervised manner, but I do believe that the user should always provide the pipeline or a list of pipeline transformations.

### From my perspective
I would like to use your code with wandb sweeps.
In this scenario, I rewrite parts of my CLI code just that the wandb sweep scheduler can supply the parameters without any modifications.
Specifically, I usually end up have CLI arguments such as _resize-scale-min_ and _resize-scale-max_, just so that it is easier to _optimize_ both values independently with wandb.
This is just one example of why I would like to use my own transformation pipeline (I also have other reasons, but I believe that some customization to the augmentation function will be done by more _experienced_ developers).
Now let's take a look at SWAV:
```python
for nc, size, mins, maxs in zip(num_crops, crop_sizes, min_scales, max_scales):
            self.augs += [aug_func(size, resize_scale=(mins, maxs), **aug_kwargs) for i in range(nc)]
        if print_augs: 
            for aug in self.augs: print(aug)
```
Here we can see that even if you allow me to use a custom `aug_func` I still need to look up the source code and modify my function signature to comply with this calling signature.
Sure, we could document this necessity, but then like in my example above, maybe I have reasons, why I would like a different signature?

It also couples parts together that, _in my opinion_, do not belong together.
The multi-crop augmentation trick was introduced in the SWaV paper, but maybe I would like to test it without the multi-crop technique because my images are very low resolution?

Plus, I will always have to look up what arguments I can pass into your augmentation function.
Here it would be nice to have some auto-complete features.

### Proposal
Instead of supplying the function and assembling the function in the init function, let's get the pipeline directly.
I would recommend making this parameter non-optional:
- The user will be aware that this pipeline will be used to generate the different views
- The augmentation pipeline stays completely customizable for the user
- The _normal_ user who want to use your augmentation pipeline can simply call your function and will get full auto-completion + documentation from it. 
    - Requires an extra wrapper that returns the pipeline, but that shouldn't be a problem with `delegates`
    - Yes, for the SWAV scenario the user would maybe need to call another function that generates the different view-pipelines, but then it is obvious that the multi-crop is strictly speaking not necessary for the SWAV callback
- The main difference for the examples would only be a single line, where the pipeline/list of pipelines is generated, but again, I believe that this makes the general flow more obvious

In general, we would then have to double-check that `pipeline.idx` is set to 0 and that either a full list for each branch is provided or a single pipeline for all branches.

I would really like to hear your comments on this and I am happy to provide some suggestion on how I would implement it if you would consider this to be a reasonable change :)

**Comment by KeremTurgutlu** [comment]
Thanks for the detailed description of your suggestion and the code example. User experience design is definitely a hard one to be honest. There is a trade off between simplicity and flexibility. My initial goal was to first of all things get the implementations right and prove that they are working as intended. It looks like we are on track with this. Second thing I had in my mind was to allow people to train their own self-supervised models with just a few lines of code similar to fastai. Of course, fastai's multilayer design allow you to have both simplicity and flexibility at the same time, you can use high level APIs and train your models without much coding or you can go to lower level APIs and adjust things as you wish easily. This type of design would be 100% ideal but I am not sure the scope of this project would require such an extensive design and effort. Mainly we have few utilities, augmentations, and mostly algorithm/paper implementations as callbacks with some custom additions/modifications.

Here are my thoughts / expectations / feedback:

1) I would really like users to at least read the paper/blog posts of the algorithms that they are intending on using. Having prior knowledge is a **must** in my opinion. The real value of this repo is that you know that you want to train models using self supervised algorithm X and you are also fastai user, then in this case you don't need to spend time implementing them from scratch or adapting other repos into fastai. If you don't know much about self supervised algorithms beyond the high level idea of that they help learning good features and they are helpful when labelled data is scarce, then you can still read the auto generated documentations/example to learn about these algorithms. I intend to make them as educational as possible. I am putting tips/tricks about that algorithm wherever I can. That being said documentation can definitely be improved though, ideally each documentation/notebook should be as good as a blog post for that algorithm. This can be a TODO :)

2) 

> Here we can see that even if you allow me to use a custom aug_func I still need to look up the source code and modify my function signature to comply with this calling signature.
> Sure, we could document this necessity, but then like in my example above, maybe I have reasons, why I would like a different signature?
> 
> It also couples parts together that, in my opinion, do not belong together.
> The multi-crop augmentation trick was introduced in the SWaV paper, but maybe I would like to test it without the multi-crop technique because my images are very low resolution?
> 
> Plus, I will always have to look up what arguments I can pass into your augmentation function.
> Here it would be nice to have some auto-complete features.

These are all valid points and I agree with you. We should have initialized aug pipelines as separate input to the callback, this will fix delegates and allow to see the args. Maybe having helpers for each algorithm like you did with `get_multi_crop_batch_pipelines` can be good enough for users that don't want to change much, e.g. just changing min max values for crops should be enough for most cases. For advanced users like, this as you mentioned will give the flexibility to modify further if needed (but support for this kind of advanced usage will be lacking, which is ok IMO).

3) 

> In general, we would then have to double-check that pipeline.idx is set to 0 and that either a full list for each branch is provided or a single pipeline for all branches.
 
This is an example of advanced usage support lack I mentioned above. Let's say if we have pipeline funcs for each algorithm such as: `simclr_aug_pipelines`, `byol_aug_pipelines`, `swav_aug_pipelines`, `moco_aug_pipelines` users would be able to see all the args via delegates which will give a better user experience and no need of reading the source code. But if they intend to change these functions or implement their owns then we can't guarantee that it will work. Maybe few warnings and tips can be put to documentations about this, such as using `split_idx=0`.

Thanks again, I think this is great, and you definitely not allow me to be lazy about this work haha :D

**Comment by kai-tub** [comment]
> This type of design would be 100% ideal but I am not sure the scope of this project would require such an extensive design and effort. Mainly we have few utilities, augmentations, and mostly algorithm/paper implementations as callbacks with some custom additions/modifications.

I do believe that later on, we can add more high-level layers. :)

> I would really like users to at least read the paper/blog posts of the algorithms that they are intending on using. Having prior knowledge is a must in my opinion.

I fully agree! But I still feel like in the second scenario, where users just quickly want to test out the feature generation, it would only be more beneficial if there was another line creating the batch augmentation pipeline and _seeing_ that the pipeline has to be passed in :)

> That being said documentation can definitely be improved though, ideally each documentation/notebook should be as good as a blog post for that algorithm. This can be a TODO :)

This is also something I hope I can help doing :) 

> For advanced users like, this as you mentioned will give the flexibility to modify further if needed (but support for this kind of advanced usage will be lacking, which is ok IMO).

Definitely! If somebody wants to generate inputs based on GANs than they should expect to do some little research on how the code is working behind the scenes :D 
And because the augmentation pipeline is so crucial, I would really like to have the flexibility. 
I am glad that you agree. :+1: 

> Maybe few warnings and tips can be put to documentations about this, such as using split_idx=0.

I do think that a couple of hints would suffice.
From what I can tell from my modifications, is that I only need to ensure that `split_idx == 0`, all augmentations work on batches and that is already everything I had to watch out for.

Ok, I just remembered that there might be cases where the input might not be `xb, yb`...
Still, just mentioning this in the documentation should be enough.
We users should just be happy, that we have the possibility to use the algorithms with fastai in the first place. :D

**Comment by KeremTurgutlu** [comment]
> But don't feel pressured to implement these suggestions or respond to my comments as fast as possible!
> I am happy working with the bleeding edge of the repository and keeping my own "patches" in my repository.
> As the, currently, only demanding user, I do not want to push you to the open-source fatigue. 😅

Haha, that's all good and these are very useful suggestions which I already had been thinking while developing but didn't spend to much time or implemented like you. I will definitely finish augmentation separation before the v1.0.0 release because it would be a breaking change. Once v.1.0.0 is out then we can start having PRs from the community and great contributors like you :D That would definitely help with scale of improvements.

**Comment by KeremTurgutlu** [comment]
This should be done now [here](https://github.com/KeremTurgutlu/self_supervised/pull/19/commits/c6fc1f48651bad398fba511a4a1c0cc600b390a9)
