### ISSUE TITLE
Fine-tune CLIP

### ISSUE THREAD

**Issue by dmoham1476** [KeremTurgutlu/self_supervised#34]
Hi Thanks for your effort on training CLIP from scratch. Could you please add code to fine-tune as well? Does this fine-tune both the text and image transformer released in CLIP repo or just the image transformer? Can we use the fine-tuned model from this code directly with the CLIP zero shot inference code?

**Comment by KeremTurgutlu** [comment]
> Hi Thanks for your effort on training CLIP from scratch. Could you please add code to fine-tune as well? 
This [script](https://github.com/KeremTurgutlu/self_supervised/blob/fastai_update/examples/training_clip.py) should do the trick.

>Does this fine-tune both the text and image transformer released in CLIP repo or just the image transformer?
Current script is going to load the pretrained CLIP model and will update all the weights during training. Freezing layers is not implemented but you can modify the script.

> Can we use the fine-tuned model from this code directly with the CLIP zero shot inference code?
There are few modifications on the `forward()` so you can check the model code. Required changes should be very minimal.
