### ISSUE TITLE
using dummy_label not working

### ISSUE THREAD

**Issue by rbunn80110** [KeremTurgutlu/self_supervised#49]
```
def get_dls(size, bs, workers=None):
    def dummy_label(o): return 0
    files = get_image_files("folder/of/images")
    tfms = [[PILImage.create, ToTensor, RandomResizedCrop(size, min_scale=1.)], 
            [dummy_label]]
    
    dsets = Datasets(files, tfms=tfms, splits=RandomSplitter(valid_pct=0.1)(files))
    
    batch_tfms = [IntToFloatTensor]
    dls = dsets.dataloaders(bs=bs, num_workers=workers, after_batch=batch_tfms)
    return dls``
```

produces this error:

AssertionError                            Traceback (most recent call last)
<ipython-input-14-6b27b52e5686> in <module>
----> 1 learn = Learner(dls, model, cbs=cbs)

~/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py in __init__(self, dls, model, loss_func, opt_func, lr, splitter, cbs, metrics, path, model_dir, wd, wd_bn_bias, train_bn, moms)
     89         if loss_func is None:
     90             loss_func = getattr(dls.train_ds, 'loss_func', None)
---> 91             assert loss_func is not None, "Could not infer loss function from the data, please pass a loss function."
     92         self.dls,self.model = dls,model
     93         store_attr(but='dls,model,cbs')

AssertionError: Could not infer loss function from the data, please pass a loss function.

When you call the learner constructor.

Should I just give it any loss function here?

**Comment by KeremTurgutlu** [comment]
Hi, can you link a notebook with full code. It would help to see the full picture. Assuming you are using a callback which implements its own loss function then yes you can pass any loss function during constructing the Learner.

**Comment by rbunn80110** [comment]
Just putting in whatever loss function appears to work.
