### ISSUE TITLE
learn.summary() raises exception with MOCO trainer

### ISSUE THREAD

**Issue by ai-padawan** [KeremTurgutlu/self_supervised#56]
Please confirm your versions of fastai, timm, kornia, fastcore, and nbdev prior to reporting a bug
- torch 1.7.0, torchvision 0.8.1, fastai 2.2.5, using latest self_supervised build as of 4/15.

**Describe the bug**
- learn.summary() raises exception when fitting, see MOCO(Callback), raise Exception("Key encoder and queue is already defined")

**To Reproduce**
- Use NB in gitrepo, insert learn.summary() before learn.fit() to repro bug

**Expected behavior**
- learn.summary() should not cause errors in fitting
- A possible workaround is to remove the exception and just reinitialize the encoder and queue and issue a warning when encoder and queue has been defined before. Not sure if this will cause training issues though...

**Comment by KeremTurgutlu** [comment]
> A possible workaround is to remove the exception and just reinitialize the encoder and queue and issue a warning when encoder and queue has been defined before. Not sure if this will cause training issues though...

I think this is a good idea.

**Comment by KeremTurgutlu** [comment]
I spent a fair amount of time on `learn.summary()` and I think I found the issue [here](https://github.com/fastai/fastai/blob/ab154927696338741e59e0ffc4774777c4a9781c/fastai/callback/hook.py#L156). This line grabs only the first element in the batch and reduces batch size to 1. I am not sure how this wasn't caught previously but it's worth asking whether it is specific to our case.

**Comment by KeremTurgutlu** [comment]
Fixed in #58
