### ISSUE TITLE
MOCO/BYOL Trainers cannot have BN layers in head

### ISSUE THREAD

**Issue by ai-padawan** [KeremTurgutlu/self_supervised#57]
Please confirm your versions of fastai, timm, kornia, fastcore, and nbdev prior to reporting a bug
- torch 1.7.0, torchvision 0.8.1, fastai 2.2.5, using latest self_supervised build as of 4/15.

**Describe the bug**
- Both MOCO and BYOL trainers cannot handle BN layers in head

```
   2035         size_prods *= size[i + 2]
   2036     if size_prods == 1:
-> 2037         raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
   2038 
   2039 


ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256])
```
**To Reproduce**
- Use NB in gitrepo, pass create_byol_model(bn=True) and/or create_moco_model(bn=True)

**Expected behavior**
- Should be able to train MOCO/BYOL with BN layers?

**Comment by KeremTurgutlu** [comment]
I am able to create models with `bn=True`, tried this in [colab](https://colab.research.google.com/drive/199Im7CiTsUJYte_3LVmyDUU_pUT37EnJ?usp=sharing) and it works fine:

```
from self_supervised.vision.moco import create_moco_model
from self_supervised.vision.byol import create_byol_model
from self_supervised.vision.barlow_twins import create_barlow_twins_model

model = create_moco_model(encoder, bn=True)
model = create_byol_model(encoder, bn=True)
model = create_barlow_twins_model(encoder, bn=True)
```

**Comment by KeremTurgutlu** [comment]
Digging even further I found the root cause regarding the MOCO Callback. Batchnorm was complaining because `self.encoder_k` is always in `train()` mode. This technically shouldn't affect the performance of MOCO pretraining but it's better to do everything by the book, so I am adding these to the callback:

```
def before_train(self):    self.encoder_k.train()
def before_validate(self): self.encoder_k.eval()
```

Thanks for opening this issue!
