### ISSUE TITLE
What is the performance of CLIP-MoCo

### ISSUE THREAD

**Issue by mathfinder** [KeremTurgutlu/self_supervised#66]
What is the performance of CLIP-MoCo compare to CLIP and MOCO

**Comment by KeremTurgutlu** [comment]
I personally didn't have a chance to run extensive experiments on it but the idea is to allow larger effective batch size by using the same idea from MoCo queue-dequeue mechanism, especially helpful when GPU resources are low. Theoretically it should work :) Will post an update if I get to running detailed experiments.
