### ISSUE TITLE
Use of obsolete kornia function name GaussianBlur

### ISSUE THREAD

**Issue by williamsdoug** [KeremTurgutlu/self_supervised#70]
RandomGaussianBlur.encodes() calls obsolete kornia function name GaussianBlur () in file self_supervised/self_supervised/augmentations.py line 25.  Function renamed RandomGaussianBlur effective Kornia release 0.5.5 per [kornia CHANGELOG.md](https://github.com/kornia/kornia/blob/c62084e036ce78bd80dc953daa33cfd893d9495e/CHANGELOG.md)

````
class RandomGaussianBlur(RandTransform):
    "Randomly apply gaussian blur with probability `p` with a value of s"
    order = 11
    def __init__(self, p=0.5, s=(8,32), same_on_batch=False, **kwargs):
        store_attr()
        super().__init__(p=p, **kwargs)

    def encodes(self, x:TensorImage):
        if isinstance(self.s, tuple): s = np.random.randint(*self.s)
        if isinstance(self.s, list):  s = np.random.randint(*self.s)
        if isinstance(self.s, int):   s = self.s
        s2 = int(s/4)*2+1
        tfm = korniatfm.GaussianBlur((s2,s2),(s,s),same_on_batch=self.same_on_batch,p=1.)
        return tfm(x)
````

**Comment by KeremTurgutlu** [comment]
Thanks for pointing this out. It's been fixed now, [commit](https://github.com/KeremTurgutlu/self_supervised/commit/5af2aab1d687cae77acef176fc276aec18fe2a2c#diff-9b94819a5bdf8c2499aa2fe6c73b250dcfc9bcde7e9998091e0ed12169c5c72f). Latest release `v.1.0.4` has this change and `pip install self-supervised` should work without any issues.
